// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW27_ErQUV7PS2OmLk1NEMpslnHUCYSBs',
    appId: '1:326837747334:android:c5410e30e54cc4a8df5b07',
    messagingSenderId: '326837747334',
    projectId: 'jasda-care-family',
    storageBucket: 'jasda-care-family.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI8MtmJAi-MD3dduviOTyb_QGANIBnzYA',
    appId: '1:326837747334:ios:7fbae28b94ab3c16df5b07',
    messagingSenderId: '326837747334',
    projectId: 'jasda-care-family',
    storageBucket: 'jasda-care-family.firebasestorage.app',
    androidClientId: '326837747334-hb2ghqs7j9a5ratc4k60vt0vghf040mq.apps.googleusercontent.com',
    iosClientId: '326837747334-9vfr5viimirbf2r96cmmd34ol85l7t2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

}